import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillFacebook, 
  AiFillLinkedin, 
  AiFillInstagram, 
  AiFillGithub
} from 'react-icons/ai';
import Image from "next/image";
import Headroom from 'react-headroom';

import benpic from '../../public/benpic.jpeg';
import web1 from '../../public/web1.png';
import web2 from '../../public/web2.png';
import web3 from '../../public/web3.png';
import web4 from '../../public/web4.png';
import web5 from '../../public/web5.png';

import java from '../../public/java.png';
import csharp from '../../public/csharp.png';
import cpp from '../../public/cpp.png';
import git from '../../public/git.png';
import github from '../../public/github.png';
import vite from '../../public/vite.png';
import cpanel from '../../public/cpanel.png';

import css from '../../public/gifs/css.gif';
import react from '../../public/gifs/react.gif';

import html from '../../public/html.png';
import js from '../../public/js.png';
import php from '../../public/php.png';
import laravel from '../../public/laravel.png';
import tailwind from '../../public/tailwind.png';

import { useState, useEffect } from "react";

const PDF_FILE_URL = 'https://react-portfolio-gamma-jet.vercel.app/Barcebal_Benedict_Obre.pdf';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const downloadFilaAtURL=(url)=>{
    const fileName = url.split('/').pop();
    const aTag = document.createElement('a');
    aTag.href=url;
    aTag.setAttribute('download',fileName);
    document.body.appendChild(aTag);
    aTag.click();
    aTag.remove();
  }
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Bndct Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headroom>
        <nav className="sticky-navbar py-10 px-10 md:px-20 xl:px-60 flex justify-between bg-gray-900 dark:bg-gray-200"> 
          <h1 className="text-md font-burtons text-yellow-300 dark:text-gray-950">Bndct</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} 
              className="cursor-pointer text-2xl text-white dark:text-gray-950"/>
            </li>
          </ul>
        </nav> 
      </Headroom>
        
      <main className="bg-gray-950 px-10 md:px-20 xl:px-60 dark:bg-gray-50">

        <section>
          <div class="bg-gray-950 dark:bg-gray-50 text-gray-50">
              <div class="pt-20 grid grid-cols-2 gap-0">
                <div>
                  <h1 class="text-3xl md:text-5xl p-2 font-burtons text-yellow-300 dark:text-gray-950">
                    Ben Obre Barcebal
                  </h1>
                  <h2 class="text-2xl md:text-3xl mb-2 dark:text-gray-950">
                    Full Stack Web Developer
                  </h2>
                  <p class="text-sm md:text-base text-gray-50 mb-4 dark:text-gray-950">
                    "As an aspiring web developer, I am committed to mastering the art of coding 
                    and design. I am eager to craft innovative and user-friendly websites that 
                    leave a lasting impression in the ever-evolving digital landscapes."
                  </p>
                </div>
                <div>
                  <div class="h-48 flex flex-wrap content-center">
                    <div className="relative mx-auto bg-yellow-300 dark:bg-yellow-200
                      rounded-full w-40 h-40 mt-20 overflow-hidden md:h-60 md:w-60">
                      <Image src={benpic} layout="fill" objectFit="cover" />
                    </div>
                  </div>
                </div>
              </div>
                <div className="flex text-5xl mt-20 justify-center gap-10 py-3 text-yellow-300">
                  <a href="https://www.facebook.com/benobre24/" target="blank">
                    <AiFillFacebook className="hover:text-gray-50 dark:text-gray-950 dark:hover:text-yellow-400" title="facebook"/>
                  </a>
                  <a href="https://www.linkedin.com/in/benedict-barcebal-24b238276/" target="blank">
                    <AiFillLinkedin className="hover:text-gray-50 dark:text-gray-950 dark:hover:text-yellow-400" title="Linkedin"/>
                  </a>
                  <a href="https://www.instagram.com/bndct24/" target="blank">
                    <AiFillInstagram className="hover:text-gray-50 dark:text-gray-950 dark:hover:text-yellow-400" title="Instagram"/>
                  </a>
                  <a href="https://github.com/venbarc" target="blank">
                    <AiFillGithub className="hover:text-gray-50 dark:text-gray-950 dark:hover:text-yellow-400" title="Github"/>
                  </a>
                </div>
                <div className="flex justify-center mt-16">
                  <div className="relative duration-300 hover:-rotate-0 -rotate-12 group border border-gray-800 border-4 overflow-hidden rounded-2xl relative h-52 w-72 p-5 flex flex-col items-start gap-4">
                    <div className="text-gray-100 dark:text-gray-950">
                      <span className="font-bold text-4xl">Resume</span>
                      <p className="text-xs">Full Stack Developer </p>
                    </div>
                    <button
                      onClick={()=>{downloadFilaAtURL(PDF_FILE_URL)}}
                      className="duration-300 hover:bg-gray-900 border hover:border-yellow-300 hover:text-yellow-300 bg-gray-50 font-semibold text-gray-900 px-3 py-2 flex flex-row items-center gap-3">
                      Download
                      <svg className="w-6 h-6 fill-current" height="100" preserveAspectRatio="xMidYMid meet" viewBox="0 0 100 100" width="100" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink">
                        <path d="M22.1,77.9a4,4,0,0,1,4-4H73.9a4,4,0,0,1,0,8H26.1A4,4,0,0,1,22.1,77.9ZM35.2,47.2a4,4,0,0,1,5.7,0L46,52.3V22.1a4,4,0,1,1,8,0V52.3l5.1-5.1a4,4,0,0,1,5.7,0,4,4,0,0,1,0,5.6l-12,12a3.9,3.9,0,0,1-5.6,0l-12-12A4,4,0,0,1,35.2,47.2Z" fillRule="evenodd"></path>
                      </svg>
                    </button>
                    <svg className="group-hover:scale-125 duration-500 absolute -bottom-0.5 -right-20 w-48 h-48 z-10 -my-2 fill-gray-50 stroke-gray-300 dark:stroke-yellow-200" viewBox="0 0 64 64"><path dataName="layer1" d="M 50.4 51 C 40.5 49.1 40 46 40 44 v -1.2 a 18.9 18.9 0 0 0 5.7 -8.8 h 0.1 c 3 0 3.8 -6.3 3.8 -7.3 s 0.1 -4.7 -3 -4.7 C 53 4 30 0 22.3 6 c -5.4 0 -5.9 8 -3.9 16 c -3.1 0 -3 3.8 -3 4.7 s 0.7 7.3 3.8 7.3 c 1 3.6 2.3 6.9 4.7 9 v 1.2 c 0 2 0.5 5 -9.5 6.8 S 2 62 2 62 h 60 a 14.6 14.6 0 0 0 -11.6 -11 z" strokeMiterlimit="10" strokeWidth="5"></path></svg>
                    <svg className="group-hover:scale-125 duration-200 absolute -bottom-0.5 -right-20 w-48 h-48 z-10 -my-2 fill-gray-50 stroke-gray-300 dark:stroke-gray-300" viewBox="0 0 64 64"><path dataName="layer1" d="M 50.4 51 C 40.5 49.1 40 46 40 44 v -1.2 a 18.9 18.9 0 0 0 5.7 -8.8 h 0.1 c 3 0 3.8 -6.3 3.8 -7.3 s 0.1 -4.7 -3 -4.7 C 53 4 30 0 22.3 6 c -5.4 0 -5.9 8 -3.9 16 c -3.1 0 -3 3.8 -3 4.7 s 0.7 7.3 3.8 7.3 c 1 3.6 2.3 6.9 4.7 9 v 1.2 c 0 2 0.5 5 -9.5 6.8 S 2 62 2 62 h 60 a 14.6 14.6 0 0 0 -11.6 -11 z" strokeMiterlimit="10" strokeWidth="2"></path></svg>
                  </div>
                </div>
          </div>
        </section>
        
        <section className="mt-20">
          <div>
            <h3 className="text-3xl py-1 text-gray-50 dark:text-gray-950 font-burtons">
              Tech Stacks
            </h3>
            <p className="text-md py-2 leading-8 text-gray-200 dark:text-gray-950">
            Commencing with the fundamentals of
          <span className="text-yellow-300 dark:text-gray-950 dark:font-bold"> HTML and CSS</span>,
          I systematically incorporated
          <span className="text-yellow-300 dark:text-gray-950 dark:font-bold"> JavaScript </span> for
          enhanced interactivity. Subsequently, my trajectory pivoted towards
          <span className="text-yellow-300 dark:text-gray-950 dark:font-bold"> PHP and Laravel </span>
          to engineer resilient web applications. Presently, my journey persists with a commitment to augmenting my proficiency, wherein I harness
          <span className="text-yellow-300 dark:text-gray-950 dark:font-bold"> React and Next.js </span>
          to fashion dynamic and responsive web experiences. Additionally, I strategically employ the
          <span className="text-yellow-300 dark:text-gray-950 dark:font-bold"> Tailwind CSS </span>
          framework to expedite the development of swift and responsive web applications, ensuring the delivery of superlative user experiences. This iterative process underscores my dedication to remaining at the forefront of technological advancements in the ever-evolving landscape of web development.
            </p>
          </div>

          <div className="grid lg:grid-cols-3 md:grid-cols-2 gap-10 mt-6">
            {/* Card 1 */}
            <div className="transform transition-transform ease-in-out hover:scale-105 text-justify 
            bg-gray-900 dark:bg-gray-200 p-10 rounded-xl" style={{ boxShadow: "6px 6px 6px 6px rgba(255, 255, 0, 0.1), 0 2px 4px -1px rgba(255, 255, 0, 0.06)" }}>
              <h3 className="text-lg text-yellow-300 dark:text-gray-950 mb-8 font-burtons pt-4 pb-2">
                Html and Css
              </h3>
              <div className="grid grid-cols-2 my-5">
                <div className="relative mx-auto bg-white dark:bg-gray-950
                  rounded-full w-28 h-28 overflow-hidden md:h-14 md:w-14">
                  <Image src={html} className="pop-image" layout="fill" objectFit="cover" />
                </div>
                <div className="relative mx-auto bg-white
                  rounded-full w-28 h-28 overflow-hidden md:h-14 md:w-14">
                  <Image src={css} className="pop-image" layout="fill" objectFit="cover" />
                </div>
              </div>
              <p className="py-2 text-gray-200 dark:text-gray-950">
                During my second year of college in 2018, I achieved mastery in HTML and CSS. 
                Over the course of nearly five years, I have applied this expertise to proficiently 
                construct and design websites.
              </p>
            </div>
            {/* Card 2 */}
            <div className="transform transition-transform ease-in-out hover:scale-105 text-justify
             bg-gray-900 dark:bg-gray-200 p-10 rounded-xl" style={{ boxShadow: "6px 6px 6px 6px rgba(255, 255, 0, 0.1), 0 2px 4px -1px rgba(255, 255, 0, 0.06)" }}>
              <h3 className="text-lg text-yellow-300 dark:text-gray-950 mb-8 font-burtons pt-4 pb-2">
                JavaScript
              </h3>
              <div className="my-5">
                <div className="relative mx-auto bg-white
                  rounded-full w-28 h-28 overflow-hidden md:h-20 md:w-20">
                  <Image src={js} className="pop-image" layout="fill" objectFit="cover" />
                </div>
              </div>
              <p className="py-2 text-gray-200 dark:text-gray-950">
                I have acquired foundational knowledge in JavaScript through comprehensive 
                exploration of its fundamentals for both dynamic and static project creation. 
                Over a span of four years, I have consistently utilized this knowledge to 
                enhance my proficiency in the language.
              </p>
            </div>
            {/* Card 3 */}
            <div className="transform transition-transform ease-in-out hover:scale-105 text-justify
             bg-gray-900 dark:bg-gray-200 p-10 rounded-xl" style={{ boxShadow: "6px 6px 6px 6px rgba(255, 255, 0, 0.1), 0 2px 4px -1px rgba(255, 255, 0, 0.06)" }}>
              <h3 className="text-lg text-yellow-300 dark:text-gray-950 mb-8 font-burtons pt-4 pb-2">
                React and Next.js
              </h3>
              <div className="my-5">
                <div className="relative mx-auto bg-white
                  rounded-full w-28 h-28 overflow-hidden md:h-20 md:w-20">
                  <Image src={react} className="pop-image" layout="fill" objectFit="cover" />
                </div>
              </div>
              <p className="py-2 text-gray-200 dark:text-gray-950">
                As of November 8, 2023, I am actively engaged in learning React and Next.js 
                for front-end development. I am committed to a continuous learning journey, 
                dedicated to honing my skills and achieving mastery in leveraging these 
                frameworks to elevate my proficiency in front-end development.
              </p>
            </div>
            {/* Card 4 */}
            <div className="transform transition-transform ease-in-out hover:scale-105 text-justify
             bg-gray-900 dark:bg-gray-200 p-10 rounded-xl" style={{ boxShadow: "6px 6px 6px 6px rgba(255, 255, 0, 0.1), 0 2px 4px -1px rgba(255, 255, 0, 0.06)" }}>
              <h3 className="text-lg text-yellow-300 dark:text-gray-950 font-burtons pt-4 ">
                PHP  
              </h3>
              <h4 className="text-sm text-yellow-300 dark:text-gray-950 font-burtons mb-8 pb-2">
                Laravel 10 to latest
              </h4>
              <div className="grid grid-cols-2 my-5">
                <div className="relative mx-auto bg-white
                  rounded-full w-28 h-28 overflow-hidden md:h-14 md:w-14">
                  <Image src={php} className="pop-image" layout="fill" objectFit="cover" />
                </div>
                <div className="relative mx-auto bg-white
                  rounded-full w-28 h-28 overflow-hidden md:h-14 md:w-14">
                  <Image src={laravel} className="pop-image" layout="fill" objectFit="cover" />
                </div>
              </div>
              <p className="py-2 text-gray-200 dark:text-gray-950">
                Since my second year of college in 2019, I have been proficiently utilizing pure 
                PHP in various projects requiring dynamic functionality. Over the past few months, 
                starting from September 2023, I have transitioned to employing the PHP Framework 
                Laravel 10, or its latest version, to further enhance the efficiency and scalability 
                of my web development projects. This strategic adoption reflects my commitment to 
                staying abreast of industry advancements and optimizing my development practices.
              </p>
            </div>
            {/* Card 5 */}
            <div className="transform transition-transform ease-in-out hover:scale-105 text-justify
             bg-gray-900 dark:bg-gray-200 p-10 rounded-xl" style={{ boxShadow: "6px 6px 6px 6px rgba(255, 255, 0, 0.1), 0 2px 4px -1px rgba(255, 255, 0, 0.06)" }}>
              <h3 className="text-lg text-yellow-300 dark:text-gray-950 font-burtons pt-4">
                Tailwind  
              </h3>
              <h4 className="text-sm text-yellow-300 dark:text-gray-950 font-burtons mb-8 pb-2">
                Css Framework
              </h4>
              <div className="my-5">
                <div className="relative mx-auto bg-white
                  rounded-full w-28 h-28 overflow-hidden md:h-20 md:w-20">
                  <Image src={tailwind} className="pop-image" layout="fill" objectFit="cover" />
                </div>
              </div>
              <p className="py-2 text-gray-200 dark:text-gray-950">
                With nearly two years of hands-on experience, I have cultivated proficiency in 
                utilizing the Tailwind CSS framework. This transition stemmed from my decision 
                to switch from Bootstrap to Tailwind, as I found Tailwind to be notably more 
                accessible and versatile, particularly in its facilitation of color customization 
                and layout flexibility. This strategic choice underscores my commitment to adopting 
                tools that not only streamline development processes but also align with the 
                evolving demands of modern web design.
              </p>
            </div>

          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-2 text-gray-50 dark:text-gray-950 font-burtons">
              Accomplished Projects
            </h3>
            <p className="text-md py-2 leading-8 text-gray-200 dark:text-gray-950">
              In my capacity as a web developer, I've successfully executed a spectrum of 
              projects encompassing HTML, CSS, JavaScript, and PHP. My proficiency in Tailwind 
              CSS is strategically employed to optimize the speed and responsiveness of web 
              applications. The adoption of React and Next.js further amplifies my capability 
              to craft dynamic and responsive web experiences. Notably, my recent incorporation 
              of Laravel 10 in PHP aligns with my commitment to remain at the forefront of industry 
              standards. Actively exploring new frameworks, my objective is to advance the 
              development of faster, more secure, and user-friendly web applications.
            </p>
          </div>
          
          <div className="grid lg:grid-cols-2 sm:grid-cols-1 gap-5">
            {/* card 1  */}
            <div class="card mx-auto text-gray-300 hover:brightness-90 transition-all group bg-gray-900 dark:bg-gray-200 hover:from-gray-800 hover:to-gray-950  m-4 rounded-lg overflow-hidden relative">
              <div class="p-8">
                <h1 class="font-burtons text-lg text-yellow-300 dark:text-gray-950 my-5">
                  Erovoutika Academy
                </h1>
                <Image src={web1} />
                <div className="flex">
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={html} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={css} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={js} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={php} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={tailwind} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                </div>
                <p class="text-gray-300 dark:text-gray-950 my-5 text-justify">
                  I bear the responsibility for the comprehensive backend development of Eira 
                  Academy for Erovoutika. Key functions under my purview include the implementation 
                  of certification processes following successful examinations and the establishment 
                  of secure payment procedures utilizing Gcash and Security Bank systems.
                </p>
                <a className="flex justify-center mx-16 md:mx-44 lg:mx-32 py-1 bg-gray-50 hover:bg-gray-900 hover:text-yellow-300 border hover:border-yellow-300 border-2 text-black text-sm font-semibold" 
                  href="https://eira.erovoutika.ph/" target="_blank">Visit here
                </a>
              </div>
              <div className="h-2 w-full bg-gradient-to-l via-yellow-300 group-hover:blur-xl blur-2xl m-auto rounded transition-all absolute bottom-0"></div>
              <div className="h-0.5 group-hover:w-full bg-gradient-to-l  via-yellow-750 group-hover:via-yellow-300 w-[70%] m-auto rounded transition-all"></div>
            </div>
            {/* card 2  */}
            <div class="card mx-auto text-gray-300 hover:brightness-90 transition-all group bg-gray-900 dark:bg-gray-200 hover:from-gray-800 hover:to-gray-950  m-4 rounded-lg overflow-hidden relative">
              <div class="p-8">
                <h1 class="font-burtons text-lg text-yellow-300 dark:text-gray-950 my-5">
                  Headturner E-Commerce
                </h1>
                <Image src={web2} />
                <div className="flex">
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={html} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={css} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={js} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={php} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={tailwind} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                </div>
                <p class="text-gray-300 dark:text-gray-950 my-5 text-justify">
                  Within the scope of this E-commerce project, I assumed the role of developing 
                  the Admin panel and overseeing the entirety of the backend infrastructure for 
                  a client. This encompassed the implementation of diverse features to enhance 
                  the project's functionality and efficiency.
                </p>
                <a className="flex justify-center mx-16 md:mx-44 lg:mx-32 py-1 bg-gray-50 hover:bg-gray-900 hover:text-yellow-300 border hover:border-yellow-300 border-2 text-black text-sm font-semibold" 
                  href="https://headturnershelmet.com/" target="_blank">Visit here
                </a>
              </div>
              <div className="h-2 w-full bg-gradient-to-l via-yellow-300 group-hover:blur-xl blur-2xl m-auto rounded transition-all absolute bottom-0"></div>
              <div className="h-0.5 group-hover:w-full bg-gradient-to-l  via-yellow-750 group-hover:via-yellow-300 w-[70%] m-auto rounded transition-all"></div>
            </div>
            {/* card 3  */}
            <div class="card mx-auto text-gray-300 hover:brightness-90 transition-all group bg-gray-900 dark:bg-gray-200 hover:from-gray-800 hover:to-gray-950  m-4 rounded-lg overflow-hidden relative">
              <div class="p-8">
                <h1 class="font-burtons text-lg text-yellow-300 dark:text-gray-950 my-5">
                  Erovoutika Main Page
                </h1>
                <Image src={web3} />
                <div className="flex">
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={html} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={css} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={js} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={php} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={tailwind} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                </div>
                <p class="text-gray-300 dark:text-gray-950 my-5">
                  I undertook the creation of the Admin interface for Erovoutika's main pages, 
                  incorporating essential functionalities such as SMTP settings for email 
                  verifications, Qr Codes, and contact us sections.
                </p>
                <a className="flex justify-center mx-16 md:mx-44 lg:mx-32 py-1 bg-gray-50 hover:bg-gray-900 hover:text-yellow-300 border hover:border-yellow-300 border-2 text-black text-sm font-semibold" 
                  href="https://erovoutika.ph/" target="_blank">Visit here
                </a>
              </div>
              <div className="h-2 w-full bg-gradient-to-l via-yellow-300 group-hover:blur-xl blur-2xl m-auto rounded transition-all absolute bottom-0"></div>
              <div className="h-0.5 group-hover:w-full bg-gradient-to-l  via-yellow-750 group-hover:via-yellow-300 w-[70%] m-auto rounded transition-all"></div>
            </div>
            {/* card 4  */}
            <div class="card mx-auto text-gray-300 hover:brightness-90 transition-all group bg-gray-900 dark:bg-gray-200 hover:from-gray-800 hover:to-gray-950  m-4 rounded-lg overflow-hidden relative">
              <div class="p-8">
                <h1 class="font-burtons text-lg text-yellow-300 dark:text-gray-950 my-5">
                  EduPlayMaker
                </h1>
                <Image src={web4} />
                <div className="flex">
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={html} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={css} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={js} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={php} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={tailwind} className="pop-image" layout="fill" objectFit="cover" />
                  </div>
                </div>
                <p className="text-gray-300 dark:text-gray-950 my-5">
                  This constitutes our final capstone project—a Quiz creator tailored for 
                  professors. The implementation integrates the Fisher Yates algorithm in 
                  quiz selection, preventing users from encountering the same sets of questions.
                </p>
                <div className="text-center text-gray-100 dark:text-gray-950 text-sm font-semibold" 
                  >Not been deployed 
                </div>
              </div>
              <div className="h-2 w-full bg-gradient-to-l via-yellow-300 group-hover:blur-xl blur-2xl m-auto rounded transition-all absolute bottom-0"></div>
              <div className="h-0.5 group-hover:w-full bg-gradient-to-l via-yellow-750 group-hover:via-yellow-300 w-[70%] m-auto rounded transition-all"></div>
            </div>
            {/* card 5  */}
            <div class="card mx-auto text-gray-300 hover:brightness-90 transition-all group bg-gray-900 dark:bg-gray-200 hover:from-gray-800 hover:to-gray-950  m-4 rounded-lg overflow-hidden relative">
              <div class="p-8">
                <h1 class="font-burtons text-lg text-yellow-300 dark:text-gray-950 my-5">
                  Five Sec MNL
                </h1>
                <Image src={web5} />
                <div className="flex">
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={html} className="pop-image" layout="fill" objectFit="cover"/>
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={css} className="pop-image" layout="fill" objectFit="cover"/>
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={js} className="pop-image" layout="fill" objectFit="cover"/>
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={php} className="pop-image" layout="fill" objectFit="cover"/>
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={tailwind} className="pop-image" layout="fill" objectFit="cover"/>
                  </div>
                  <div className="relative mt-5 mx-auto bg-white
                    rounded-full w-12 h-12 overflow-hidden md:h-14 md:w-14">
                    <Image src={laravel} className="pop-image" layout="fill" objectFit="cover"/>
                  </div>
                </div>
                <p class="text-gray-300 dark:text-gray-950 my-5">
                  Engaged in my ongoing project, I am actively collaborating with my partner
                  to establish and develop our thrift clothing E-commerce business.
                </p>
                <div className="text-center text-gray-100 dark:text-gray-950 text-sm font-semibold" 
                  >In progress
                </div>
              </div>
              <div className="h-2 w-full bg-gradient-to-l via-yellow-300 group-hover:blur-xl blur-2xl m-auto rounded transition-all absolute bottom-0"></div>
              <div className="h-0.5 group-hover:w-full bg-gradient-to-l  via-yellow-750 group-hover:via-yellow-300 w-[70%] m-auto rounded transition-all"></div>
            </div>
          </div>
        </section>

        <section className="pb-32">
          <h3 className="text-3xl py-1 text-gray-50 dark:text-gray-950 font-burtons">
            Others
          </h3>
          <p className="text-md py-2 mb-4 leading-8 text-gray-200 dark:text-gray-950">
            Additionally, I possess a background in Object-Oriented Programming (OOP), 
            with proficiency in Java, C#, and C++. I leverage Git and GitHub for code 
            tracking and collaborative team projects. Furthermore, I am adept at utilizing 
            Vite for efficient development, and notably, I have expertise in deploying 
            and managing websites through CPanel hosting.
          </p>
          <div className="grid grid-cols-4 md:grid-cols-5 lg:grid-cols-7 justify-center pt-4 gap-8 lg:gap-4 lg:mx-24">
            <Image src={java} />
            <Image src={csharp} />
            <Image src={cpp} />
            <Image src={git} />
            <Image src={github} />
            <Image src={vite} className="w-[64px] h-auto"/>
            <Image src={cpanel} className="w-[64px] h-auto"/>
          </div>
        </section>

        <footer className="py-10 bg-gray-900 dark:bg-gray-200  text-center">
          <p className="text-gray-300 dark:text-gray-950  text-center text-sm mb-2">
            <span className="font font-burtons">developed by bndct</span> @2023 
          </p>
          <p className="text-gray-200 dark:text-gray-950 text-center text-sm">
            bentf24@gmail.com | 09393370186 | Makati City
          </p>
        </footer>
      </main>
      
    </div>
  )
}
